# Generated by Django 3.2.13 on 2022-10-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
