# Generated by Django 3.2.13 on 2022-10-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_commment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='score',
        ),
    ]
